name: automerge
on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: pnpm run intall, build, and test-doc-name
        run: |
          cd ./test
          nci
          nr test

      - name: auto-merge
        uses: 'pascalgn/automerge-action@v0.15.3'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: ''
          UPDATE_METHOD: 'rebase'
